"""Buy or Wait? - Foundational Data Layer Package."""

from .models import (
    FinancialProfile,
    FinancialEvent,
    PaymentOption,
    ExchangeRate,
    Message,
    ImageMetadata,
    FinancialRequest,
)
from .canonical import (
    CanonicalEvent,
    CanonicalLedger,
    Direction,
    CashImpactType,
    RecurrenceClassification,
)
from .reconciliation import (
    reconcile_events,
    reconcile_single_event,
    ActionType,
    ExchangeRateNotFoundError,
)
from .image_resolution import (
    ImageExtractionResult,
    IMAGE_DOCUMENT_PROFILES,
    extract_all_images,
    resolve_ledger_with_images,
)
from .recurrence import (
    RecurrenceFrequency,
    AmountForecastingRule,
    RecurrenceSeries,
    FutureEvent,
    SuppressedForecast,
    FutureExpansionResult,
    detect_recurrence_for_user,
    detect_all_recurrence,
    expand_future_events,
)
from .parsers import (
    parse_decimal,
    parse_date,
    parse_datetime,
    parse_int,
    parse_bool,
    parse_pipe_tuple,
)
from .validators import ValidationError, validate_columns
from .loaders import (
    Dataset,
    load_dataset,
    load_profiles,
    load_events,
    load_payment_options,
    load_exchange_rates,
    load_messages,
    load_images,
    load_requests,
)
from .simulator import (
    EventPriority,
    SimulatedEvent,
    FinancialState,
    EventTransition,
    SafetyFloorBreach,
    DailySnapshot,
    SimulationResult,
    create_initial_state,
    simulate_user,
    simulated_event_from_canonical,
    simulated_event_from_future,
)
from .safe_to_pay import (
    CURRENCY_QUANTUM,
    SafeToPayCertificate,
    get_currency_quantum,
    make_candidate_purchase_event,
    is_purchase_safe,
    calculate_amount_safe_to_pay,
    calculate_earliest_full_payment_date,
    evaluate_request_safe_to_pay,
)

__all__ = [
    "FinancialProfile",
    "FinancialEvent",
    "PaymentOption",
    "ExchangeRate",
    "Message",
    "ImageMetadata",
    "FinancialRequest",
    "CanonicalEvent",
    "CanonicalLedger",
    "Direction",
    "CashImpactType",
    "RecurrenceClassification",
    "reconcile_events",
    "reconcile_single_event",
    "ActionType",
    "ExchangeRateNotFoundError",
    "ImageExtractionResult",
    "IMAGE_DOCUMENT_PROFILES",
    "extract_all_images",
    "resolve_ledger_with_images",
    "RecurrenceFrequency",
    "AmountForecastingRule",
    "RecurrenceSeries",
    "FutureEvent",
    "SuppressedForecast",
    "FutureExpansionResult",
    "detect_recurrence_for_user",
    "detect_all_recurrence",
    "expand_future_events",
    "ValidationError",
    "validate_columns",
    "parse_decimal",
    "parse_date",
    "parse_datetime",
    "parse_int",
    "parse_bool",
    "parse_pipe_tuple",
    "Dataset",
    "load_dataset",
    "load_profiles",
    "load_events",
    "load_payment_options",
    "load_exchange_rates",
    "load_messages",
    "load_images",
    "load_requests",
    "EventPriority",
    "SimulatedEvent",
    "FinancialState",
    "EventTransition",
    "SafetyFloorBreach",
    "DailySnapshot",
    "SimulationResult",
    "create_initial_state",
    "simulate_user",
    "simulated_event_from_canonical",
    "simulated_event_from_future",
    "CURRENCY_QUANTUM",
    "SafeToPayCertificate",
    "get_currency_quantum",
    "make_candidate_purchase_event",
    "is_purchase_safe",
    "calculate_amount_safe_to_pay",
    "calculate_earliest_full_payment_date",
    "evaluate_request_safe_to_pay",
    "SpendingTrend",
    "IncomeStability",
    "ExpenseStability",
    "RecurringStreamSummary",
    "UpcomingObligationSummary",
    "UserFinancialState",
    "compute_monthly_equivalent",
    "build_user_financial_state",
    "evaluate_user_financial_state",
]

from .user_state import (
    SpendingTrend,
    IncomeStability,
    ExpenseStability,
    RecurringStreamSummary,
    UpcomingObligationSummary,
    UserFinancialState,
    compute_monthly_equivalent,
    build_user_financial_state,
    evaluate_user_financial_state,
)



